//>>built
define("esri/dijit/GeocodeMatch","require dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/dom-construct dojo/dom-style dojo/Evented dojo/on dojo/uacss dijit/_WidgetBase dijit/Menu dijit/MenuItem dgrid/OnDemandGrid dgrid/Selection dgrid/Keyboard dojo/store/Memory esri/kernel esri/graphic esri/InfoTemplate esri/geometry/Extent esri/geometry/Point esri/layers/GraphicsLayer esri/symbols/SimpleMarkerSymbol esri/tasks/locator esri/tasks/AddressCandidate dojo/i18n!esri/dijit/GeocodeMatch/nls/master esri/dijit/GeocodeMatch/Popup".split(" "),
function(m,n,f,s,g,p,t,k,u,v,w,x,y,z,A,q,B,l,C,r,D,E,h,F,G,e,H){m=n([v,t],{loaded:!1,basePath:m.toUrl("esri/dijit/GeocodeMatch/"),_locatorURL:"http://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer",_hasCustomPoint:!1,_gridMenuHeight:30,constructor:function(a,b){n.safeMixin(this,a);this.map&&(this._locator=new F(this._locatorURL),this._columns=[{label:e.match.columnLabelAddress,field:"address"},{label:e.match.columnLabelType,field:"Addr_type"},{label:e.match.columnLabelScore,field:"score"},
{label:e.match.columnLabelMatched,field:"matched",formatter:function(a){return a},get:f.hitch(this,function(a){return a.matched?"\x3cimg src\x3d'"+this.basePath.toString()+"images/save.png' /\x3e":""})}],this._symbol=(new h).setStyle(h.STYLE_CIRCLE).setColor([96,161,234,0.5]),this._matchSymbol=(new h).setStyle(h.STYLE_CIRCLE).setColor("#5FFB17"),this._highlightSymbol=(new h).setStyle(h.STYLE_CIRCLE).setColor("#FFFF00"))},postCreate:function(){this.inherited(arguments);this.graphicsLayer=new E;this._infoTemplate=
new C;this._infoTemplate.setTitle(e.match.infoWindowTitle);this._infoTemplate.setContent(f.hitch(this,this._getInfoTemplateContent));this.graphicsLayer.setInfoTemplate(this._infoTemplate);this.map.addLayer(this.graphicsLayer);this._createContainerNodes();this._createGridMenu();var a=n([y,z,A]);this.store=new q({data:"",idProperty:e.match.idProperty});this.grid=new a({store:this.store,noDataMessage:e.match.noDataMsg,selectionMode:"extended",allowSelectAll:!0,cellNavigation:!1,columns:this._columns},
this._gridRef);this._resizeGrid();var b=this.map;this._listenerHandles=[k(window,"resize",f.hitch(this,function(){this._resizeGrid()})),k(this.grid,"dgrid-deselect",f.hitch(this,function(){this.currentSelectedRow=this.currentSelectedRowId=null})),k(this.grid,"dgrid-select",f.hitch(this,function(a){this.graphicsLayer.graphics.forEach(f.hitch(this,function(a){a.attributes&&(a.attributes.type===e.customLabel&&!1===a.attributes.matched)&&(this.graphicsLayer.remove(a),b.infoWindow.hide())}));var c=a.rows[0].data.location;
this.currentSelectedRowId=a.rows[0].data.id;this.currentSelectedRow=a.rows[0].data;b.centerAt(c).then(f.hitch(this,function(){b.infoWindow.setFeatures([this.graphicsLayer.graphics[this.currentSelectedRowId]]);b.infoWindow.show(c)}))})),k(this.map,"click",f.hitch(this,function(a){this.graphicsLayer.graphics.forEach(f.hitch(this,function(a){a.attributes&&(a.attributes.type===e.customLabel&&!1===a.attributes.matched)&&(this.graphicsLayer.remove(a),b.infoWindow&&b.infoWindow.hide())}));if(a.graphic)a.graphic.attributes&&
a.graphic.attributes.id&&(this.grid.clearSelection(),this.grid.select(a.graphic.attributes.id));else{a=new D(a.mapPoint.x,a.mapPoint.y,this.map.spatialReference);var c=new l(a,this._highlightSymbol);c.setAttributes({type:e.customLabel,matched:!1});this.graphicsLayer.add(c);b.infoWindow.setFeatures([c]);b.infoWindow.show(a)}}))]},startup:function(){this.inherited(arguments);this.grid.startup();this.map.loaded?(this.loaded=!0,this.emit("load",{})):k(this.map,"load",f.hitch(this,function(){this.loaded=
!0;this.emit("load",{})}))},geocodeAddress:function(a,b){this._resetMapState();this._resetAppState();var d=new s,c={address:{address:a},outFields:["*"]};this._locator.outSpatialReference=this.map.spatialReference;this._locator.addressToLocations(c).then(f.hitch(this,function(b){var c;for(c=0;c<b.length;c++)b[c].id=c,b[c].matched=!1,b[c].Addr_type=b[c].attributes.Addr_type;this.store=new q({data:b});this.grid.set("store",this.store);this._updateMapGraphics();this.lastGeocodeResults=b;this.lastAddress=
a;d.resolve(b)}));return d.promise},destroy:function(){this._listenerHandles.forEach(function(a){a.remove()});this.Popup&&(this.Popup.destroy(),this.Popup=null);this.grid&&this.grid.destroy();this.store=this._columns=this.grid=null;g.empty(this._gridMenuRef);this.gridMenu=null;this.map&&(this.map.infoWindow.clearFeatures(),this.map.infoWindow.hide(),this.map.removeLayer(this.graphicsLayer));this.map=this.graphicsLayer=this._infoTemplate=this._locator=null;this.inherited(arguments)},_matchCustomFeature:function(a){var b,
d;!0===this._hasCustomPoint&&(this.store.data.forEach(f.hitch(this,function(a){a.address===e.match.userCreatedLabel&&this.store.data.splice(this.store.data.indexOf(a),1)})),this.graphicsLayer.graphics.forEach(f.hitch(this,function(a){a.attributes&&a.attributes.type===e.customLabel&&this.graphicsLayer.remove(a)})),this.currentMatch=null);d=this.store.data.length;b=new G;b.address=e.match.userCreatedLabel;b.id=d;b.Addr_type=e.customLabel;b.matched=!1;b.location=a.geometry;b.score="-";a.attributes.id=
d;a.attributes.matched=!0;this.store.data.push(b);this._hasCustomPoint=!0;this._matchFeature(d)},_matchFeature:function(a){var b=this.store.data,d=this.graphicsLayer.graphics,c=this.currentMatch;null===c?(b[a].matched=!0,!1!==this.map&&(d[a].attributes.matched=!0,d[a].attributes.id=a,d[a].setSymbol(this._matchSymbol),d[a].getDojoShape().moveToFront())):(b[a].matched=!0,b[c].matched=!1,d[c].attributes.matched=!1,d[c].setSymbol(this._symbol),d[a].attributes.matched=!0,d[a].attributes.id=a,d[a].setSymbol(this._matchSymbol),
d[a].getDojoShape().moveToFront(),d[c].attributes.type===e.customLabel&&d[a].attributes.type!==e.customLabel&&(this.graphicsLayer.remove(d[c]),b.splice(b.indexOf(b[c]),1),this._hasCustomPoint=!1));this.currentMatch=a;this.emit("match",{address:b[a].address,location:b[a].location});this.grid.refresh()},_resetMapState:function(){this.Popup&&(this.Popup.map.infoWindow.hide(),this.Popup.map.infoWindow.clearFeatures());this.grid.clearSelection()},_updateMapGraphics:function(){var a=this.store.data,b=this._symbol,
d,c,e=[];this.graphicsLayer.clear();this.graphicsLayer.clear();if(1===a.length)d=!0===a[0].matched?new l(a[0].location,this._matchSymbol):new l(a[0].location,b),d.setAttributes({id:0,matched:a[0].matched,type:a[0].Addr_type}),e.push(d);else if(1<a.length)for(c=0;c<a.length;c++)d=!0===a[c].matched?new l(a[c].location,this._matchSymbol):new l(a[c].location,b),d.setAttributes({id:a[c].id,matched:a[c].matched,type:a[c].Addr_type}),e.push(d);0!==a.length&&(a=this._calcGraphicsExtent(e),this.map.setExtent(a,
!0).then(f.hitch(this,function(){for(c=0;c<e.length;c++)this.graphicsLayer.add(e[c])})))},_calcGraphicsExtent:function(a){var b=a[0].geometry,d=b.getExtent(),c,e,f=a.length;null===d&&(d=new r(b.x,b.y,b.x,b.y,b.spatialReference));for(e=1;e<f;e++)b=a[e].geometry,c=b.getExtent(),null===c&&(c=new r(b.x,b.y,b.x,b.y,b.spatialReference)),d=d.union(c);return d},_createContainerNodes:function(){this._gridWrapperRef=g.create("div",{"class":"esriMatchContainer"},this.domNode);this._gridMenuRef=g.create("div",
{"class":"esriMatchHeader",style:"height:"+this._gridTopDivHeight+"px;"},this._gridWrapperRef);this._gridMenuLeftSpanRef=g.create("span",{"class":"esriMatchTitle",innerHTML:e.match.gridTitle},this._gridMenuRef);this._gridMenuRightRef=g.create("div",{"class":"esriMatchOptions"},this._gridMenuRef);this._gridMenuRightSpanRef=g.create("span",{innerHTML:e.match.tableOptionsLabel},this._gridMenuRightRef);this._gridMenuRightArrowRef=g.create("div",{"class":"esriSpriteArrow"},this._gridMenuRightRef);this._gridRef=
g.create("div",{},this._gridWrapperRef)},_createGridMenu:function(){this.gridMenu=new w({targetNodeIds:[this._gridMenuRightRef],leftClickToOpen:"true"});this.gridMenu.addChild(new x({label:e.match.mapAllCandidatesLabel,onClick:f.hitch(this,function(){this._resetMapState();this._updateMapGraphics()})}));this.gridMenu.startup()},_resizeGrid:function(){p.set(this._gridRef,"height",p.get(this._gridWrapperRef,"height")-this._gridMenuHeight+"px")},_getInfoTemplateContent:function(a){this.Popup=new H({geocodeMatch:this,
geocodeAddress:this.lastAddress,rowData:this.store.data[a.attributes.id],map:this.map,graphicsLayer:this.graphicsLayer,graphic:a},g.create("div"));return this.Popup.domNode},_resetAppState:function(){this.currentSelectedRow=this.lastGeocodeResults=this.lastAddress=this.currentMatch=null;this.store.data=null;this._hasCustomPoint=!1}});u("extend-esri")&&f.setObject("dijit.GeocodeMatch",m,B);return m});
//@ sourceMappingURL=GeocodeMatch.js.map