//>>built
define("esri/arcgis/csv","dojo/_base/lang dojo/_base/array dojo/_base/Deferred dojo/sniff dojo/number dojox/data/CsvStore esri/kernel esri/config esri/request esri/SpatialReference esri/geometry/Point esri/geometry/Geometry esri/geometry/jsonUtils esri/geometry/webMercatorUtils".split(" "),function(h,d,z,r,K,L,M,A,N,x,O,s,B,C){function D(a){var b=0,c="";d.forEach([","," ",";","|","\t"],function(e){var d=a.split(e).length;d>b&&(b=d,c=e)});return c}function E(a,b){if(!a||"[object Date]"!==Object.prototype.toString.call(a)||
isNaN(a.getTime()))return!1;var c=!0;if(r("chrome")&&/\d+\W*$/.test(b)){var e=b.match(/[a-zA-Z]{2,}/);if(e){for(var c=!1,d=0,m=e.length,u=/^((jan(uary)?)|(feb(ruary)?)|(mar(ch)?)|(apr(il)?)|(may)|(jun(e)?)|(jul(y)?)|(aug(ust)?)|(sep(tember)?)|(oct(ober)?)|(nov(ember)?)|(dec(ember)?)|(am)|(pm)|(gmt)|(utc))$/i;!c&&d<=m&&!(c=!u.test(e[d]));)d++;c=!c}}return c}function F(a,b,c){var e=a.indexOf("\n"),e=h.trim(a.substr(0,e)),g=b.columnDelimiter;g||(g=D(e));var m=new L({data:a,separator:g});a=9>r("ie")?
750:1001;m.fetch({start:0,count:a,onComplete:function(a,e){var f=0,n={layerDefinition:b.layerDefinition,featureSet:{features:[],geometryType:"esriGeometryPoint"}},k=n.layerDefinition.objectIdField;!k&&!d.some(n.layerDefinition.fields,function(a){return"esriFieldTypeOID"==a.type?(k=a.name,!0):!1})&&(n.layerDefinition.fields.push({name:"__OBJECTID",alias:"__OBJECTID",type:"esriFieldTypeOID",editable:!1,domain:null}),k="__OBJECTID");var g,h,t=m._attributes,r=[],s=[];d.forEach(n.layerDefinition.fields,
function(a,f){"esriFieldTypeDate"===a.type?r.push(a.name):("esriFieldTypeDouble"===a.type||"esriFieldTypeInteger"===a.type)&&s.push(a.name)});b.locationInfo&&"coordinates"===b.locationInfo.locationType?(g=b.locationInfo.latitudeFieldName,h=b.locationInfo.longitudeFieldName):d.forEach(t,function(a){var f;f=d.indexOf(G,a.toLowerCase());-1!==f&&(g=a);f=d.indexOf(H,a.toLowerCase());-1!==f&&(h=a)},this);if(!g||!h)setTimeout(function(){console.error("File does not seem to contain fields with point coordinates.")},
1);else{var t=0,w=a.length;for(t;t<w;t++){if(1E3<=n.featureSet.features.length){setTimeout(function(){console.error("1000 feature limit reached. Unable to load any more data.")},1);break}var v=a[t],q=m.getAttributes(v),p={};d.forEach(q,function(a,f){if(a){var b=a;0===a.length&&d.forEach(n.layerDefinition.fields,function(f,k){f.name==="attribute_"+(k-1)&&(a="attribute_"+(k-1))});if(d.some(r,function(f){return f===a})){var b=m.getValue(v,b),k=new Date(b);p[a]=E(k,b)?k.getTime():null}else if(d.some(s,
function(f){return f===a})){k=K.parse(m.getValue(v,b));if((a==g||a==h)&&(isNaN(k)||181<Math.abs(k)))k=parseFloat(m.getValue(v,b));isNaN(k)?p[a]=null:p[a]=k}else p[a]=m.getValue(v,b)}});p[k]=f;f++;var q=p[g],y=p[h];null==y||(null==q||isNaN(q)||isNaN(y))||(q={geometry:(new O(y,q,new x({wkid:4326}))).toJson(),attributes:p},n.featureSet.features.push(q))}n.layerDefinition.name="csv";c&&c(n)}},onError:function(a){console.error("Error fetching items from CSV store: ",a)}});return!0}function w(a,b,c,e,g,
m){0===a.length&&g(null);var u=B.getGeometryType(b),l=[];d.forEach(a,function(a){a=new u(a);a.spatialReference=c;l.push(a)},this);b=[102113,102100,3857];c.wkid&&4326===c.wkid&&e.wkid&&-1<d.indexOf(b,e.wkid)?(d.forEach(l,function(a){a.xmin?(a.xmin=Math.max(a.xmin,-180),a.xmax=Math.min(a.xmax,180),a.ymin=Math.max(a.ymin,-89.99),a.ymax=Math.min(a.ymax,89.99)):a.rings?d.forEach(a.rings,function(a){d.forEach(a,function(a){a[0]=Math.min(Math.max(a[0],-180),180);a[1]=Math.min(Math.max(a[1],-89.99),89.99)},
this)},this):a.paths?d.forEach(a.paths,function(a){d.forEach(a,function(a){a[0]=Math.min(Math.max(a[0],-180),180);a[1]=Math.min(Math.max(a[1],-89.99),89.99)},this)},this):a.x&&(a.x=Math.min(Math.max(a.x,-180),180),a.y=Math.min(Math.max(a.y,-89.99),89.99))},this),a=[],d.forEach(l,function(b){b=C.geographicToWebMercator(b);102100!==e.wkid&&(b.spatialReference=e);a.push(b.toJson())},this),g(a)):null!==c.wkid&&-1<d.indexOf(b,c.wkid)&&null!==e.wkid&&4326===e.wkid?(a=[],d.forEach(l,function(b){a.push(C.webMercatorToGeographic(b).toJson())},
this),g(a)):(b=function(b,c){b&&b.length===a.length?(a=[],d.forEach(b,function(b){b&&(b.rings&&0<b.rings.length&&0<b.rings[0].length&&0<b.rings[0][0].length&&!isNaN(b.rings[0][0][0])&&!isNaN(b.rings[0][0][1])||b.paths&&0<b.paths.length&&0<b.paths[0].length&&0<b.paths[0][0].length&&!isNaN(b.paths[0][0][0])&&!isNaN(b.paths[0][0][1])||b.xmin&&!isNaN(b.xmin)&&b.ymin&&!isNaN(b.ymin)||b.x&&!isNaN(b.x)&&b.y&&!isNaN(b.y))?a.push(b.toJson()):a.push(null)},this),g(a)):m(b,c)},A.defaults.geometryService?A.defaults.geometryService.project(l,
e,h.hitch(this,b),m):g(null))}function I(a,b){var c=[102113,102100,3857];return a&&b&&a.wkid===b.wkid&&a.wkt===b.wkt||a&&b&&a.wkid&&b.wkid&&-1<d.indexOf(c,a.wkid)&&-1<d.indexOf(c,b.wkid)?!0:!1}function J(a,b,c,e){if(a.featureSet&&0!==a.featureSet.features.length)if(I(c,b))e(a);else{var g=function(b){var c=[];d.forEach(a.featureSet.features,function(a,e){b[e]&&(a.geometry=b[e],c.push(a))},this);e(a)},m=function(b,c){console.error("error projecting featureSet ("+a.layerDefinition.name+"). Final try.");
e(a)},u=function(e,d){console.error("error projecting featureSet ("+a.layerDefinition.name+"). Try one more time.");w(l,a.featureSet.geometryType,b,c,h.hitch(this,g),h.hitch(this,m))};if(a.featureSet.features&&0<a.featureSet.features.length){var l=[];d.forEach(a.featureSet.features,function(b){if(b.geometry.toJson)l.push(b.geometry);else{var c=B.getGeometryType(a.featureSet.geometryType);l.push(new c(b.geometry))}});b.toJson||(b=new x(b));c.toJson||(c=new x(c));w(l,a.featureSet.geometryType,b,c,h.hitch(this,
g),h.hitch(this,u))}else e(a)}}var G="lat latitude y ycenter latitude83 latdecdeg POINT-Y".split(" "),H="lon lng long longitude x xcenter longitude83 longdecdeg POINT-X".split(" ");s={latFieldStrings:G,longFieldStrings:H,buildCSVFeatureCollection:function(a){var b=new z,c=function(a){b.callback(a)};N({url:a.url,handleAs:"text",load:function(b){F(b,a,h.hitch(this,c))},error:function(a){console.error("error: "+a)}},{usePost:!1});return b},projectFeatureCollection:function(a,b,c){var d=new z;c||(c=new x({wkid:4326}));
J(a,c,b,h.hitch(this,function(a){d.callback(a)}));return d},generateDefaultPopupInfo:function(a){var b={esriFieldTypeDouble:1,esriFieldTypeSingle:1},c={esriFieldTypeInteger:1,esriFieldTypeSmallInteger:1},e={esriFieldTypeDate:1},g=null;a=d.map(a.layerDefinition.fields,h.hitch(this,function(a){"NAME"===a.name.toUpperCase()&&(g=a.name);var d="esriFieldTypeOID"!==a.type&&"esriFieldTypeGlobalID"!==a.type&&"esriFieldTypeGeometry"!==a.type,l=null;if(d){var f=a.name.toLowerCase();if(-1<",stretched value,fnode_,tnode_,lpoly_,rpoly_,poly_,subclass,subclass_,rings_ok,rings_nok,".indexOf(","+
f+",")||-1<f.indexOf("area")||-1<f.indexOf("length")||-1<f.indexOf("shape")||-1<f.indexOf("perimeter")||-1<f.indexOf("objectid")||f.indexOf("_")===f.length-1||f.indexOf("_i")===f.length-2&&1<f.length)d=!1;a.type in c?l={places:0,digitSeparator:!0}:a.type in b?l={places:2,digitSeparator:!0}:a.type in e&&(l={dateFormat:"shortDateShortTime"})}return h.mixin({},{fieldName:a.name,label:a.alias,isEditable:!0,tooltip:"",visible:d,format:l,stringFieldOption:"textbox"})}));return{title:g?"{"+g+"}":"",fieldInfos:a,
description:null,showAttachments:!1,mediaInfos:[]}},_getSeparator:D,_isValidDate:E,_processCsvData:F,_projectGeometries:w,_sameSpatialReference:I,_projectFeatureSet:J};r("extend-esri")&&h.setObject("arcgis.csv",s,M);return s});
//@ sourceMappingURL=csv.js.map